const fs=require('fs'),path=require('path');
const dir=__dirname;
const data=f=>'data:image/png;base64,'+fs.readFileSync(path.resolve(dir,f)).toString('base64');
const assets={original:data('../../resources/images/background.png'),digits:[1,0,0,9].map(n=>data('../../resources/images/digits/digit-'+n+'.png'))};
const html=`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Starry Digits · живое небо</title><style>
*{box-sizing:border-box}body{margin:0;background:#10151c;color:#e9edf2;font:16px system-ui}main{max-width:1080px;margin:auto;padding:36px 24px}h1{font-size:32px;margin:8px 0}p{color:#aab7c7;line-height:1.55}.eyebrow{color:#81d9e9;font-size:12px;letter-spacing:2px}.panels{display:flex;gap:32px;flex-wrap:wrap;align-items:start;margin:30px 0}figure{margin:0}figcaption{margin-top:12px;color:#9badbf;font-size:14px}canvas{image-rendering:pixelated;background:black;display:block;max-width:100%;height:auto;border-radius:3px}#animated{width:400px}#original{width:200px}.screen{padding:16px;background:#06080b;border:1px solid #303b49;border-radius:22px;max-width:100%}.controls{display:flex;align-items:center;gap:18px;flex-wrap:wrap;background:#1c2530;padding:18px;border-radius:14px}button,select{font:inherit;color:#f0f4fa;background:#304253;border:1px solid #536779;padding:8px 12px;border-radius:7px;cursor:pointer}label{display:flex;gap:8px;align-items:center}input[type=range]{width:180px;accent-color:#65d5e7}.note{max-width:760px;font-size:14px}.strip{display:flex;overflow:auto;gap:8px;padding:16px 0}.strip button{padding:4px;background:#080d13}.strip canvas{width:80px}.strip button.active{outline:2px solid #65d5e7}#status{font-variant-numeric:tabular-nums;color:#81d9e9}a{color:#81d9e9}</style>
<main><div class="eyebrow">STARRY DIGITS / ANIMATION STUDY 02</div><h1>Живое ночное небо</h1><p>Воздушные потоки Ван Гога · 200 × 228 пикселей · палитра Pebble, до 64 цветов</p>
<div class="panels"><figure><div class="screen"><canvas id="animated" width="200" height="228"></canvas></div><figcaption>Анимация · увеличение <span id="zoomText">2×</span></figcaption></figure><figure><div class="screen"><canvas id="original" width="200" height="228"></canvas></div><figcaption>Исходный фон · 1×</figcaption><p class="note">48 кадров течения по траекториям.<br>Время — оригинальные bitmap-цифры.<br>Луна и город закреплены пиксель в пиксель.</p><p id="status">Загрузка…</p></figure></div>
<div class="controls"><button id="play">Пауза</button><label>Кадр <input id="frame" type="range" min="0" max="47" value="0"></label><label>Скорость <select id="fps"><option value="2">2 кадр/с</option><option value="4">4 кадр/с</option><option value="6">6 кадр/с</option><option value="8" selected>8 кадр/с</option><option value="12">12 кадр/с</option></select></label><label><input id="time" type="checkbox" checked>Время</label><label>Масштаб <select id="zoom"><option value="1">1×</option><option value="2" selected>2×</option><option value="3">3×</option></select></label><button id="save">Скачать кадр PNG</button></div>
<div class="strip" id="strip"></div><p class="note">Слои: исходная луна и город → движущиеся мазки сияния → неподвижные цифры. Мазки текут снизу вверх и огибают луну; геометрия потоков постоянна. Цикл замкнут математически, без обратного проигрывания. Это HTML-прототип: работа на часах и расход батареи пока не проверялись.</p></main>
<script>const assets=${JSON.stringify(assets)};
const $=id=>document.getElementById(id);let frames=[],index=0,playing=true,last=0,colors=new Set();const ctx=$('animated').getContext('2d');
const load=src=>new Promise((resolve,reject)=>{let i=new Image;i.onload=()=>resolve(i);i.onerror=reject;i.src=src});
function quantize(c){let x=c.getContext('2d'),d=x.getImageData(0,0,200,228);for(let i=0;i<d.data.length;i+=4){for(let k=0;k<3;k++)d.data[i+k]=Math.round(d.data[i+k]/85)*85;d.data[i+3]=255;colors.add(d.data[i]+','+d.data[i+1]+','+d.data[i+2])}x.putImageData(d,0,0);return c}
function canvas(){let c=document.createElement('canvas');c.width=200;c.height=228;return c}
let digits=[],orig;function overlay(c){if(!$('time').checked)return;digits.forEach((d,i)=>c.drawImage(d,8+(i%2)*48,16+Math.floor(i/2)*58,48,58))}
function draw(){ctx.clearRect(0,0,200,228);ctx.drawImage(frames[index],0,0);overlay(ctx);let o=$('original').getContext('2d');o.clearRect(0,0,200,228);o.drawImage(orig,0,0);overlay(o);$('frame').value=index;$('status').textContent='Кадр '+(index+1)+' / 48 · '+colors.size+' цветов фона · цикл '+(48/Number($('fps').value)).toFixed(1)+' с';document.querySelectorAll('.strip button').forEach((b,i)=>b.classList.toggle('active',i===Math.floor(index/4)))}
function pause(){playing=false;$('play').textContent='Воспроизвести'}
// Curvilinear flow coordinates. All positions are fixed; only brush texture travels.
const N=48, W=200,H=228,TAU=Math.PI*2;
const controls=[[ -24,143],[4,164],[42,179],[82,184],[119,174],[147,158],[157,135],[163,115],[177,94],[182,78],[171,64],[149,57]];
function curve(points){let out=[];for(let i=0;i<points.length-1;i++){let a=points[Math.max(0,i-1)],b=points[i],c=points[i+1],d=points[Math.min(points.length-1,i+2)];for(let j=0;j<32;j++){let t=j/32,t2=t*t,t3=t2*t;out.push([0,1].map(k=>.5*((2*b[k])+(-a[k]+c[k])*t+(2*a[k]-5*b[k]+4*c[k]-d[k])*t2+(-a[k]+3*b[k]-3*c[k]+d[k])*t3)))}}return out}
function makeFrames(original){let base=canvas(),bctx=base.getContext('2d');bctx.drawImage(original,0,0);const src=bctx.getImageData(0,0,W,H).data,path=curve(controls),cum=[0];for(let i=1;i<path.length;i++)cum.push(cum[i-1]+Math.hypot(path[i][0]-path[i-1][0],path[i][1]-path[i-1][1]));
const map=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++){let best=1e9,idx=0;for(let k=0;k<path.length;k++){let d=(x-path[k][0])**2+(y-path[k][1])**2;if(d<best){best=d;idx=k}}let p=path[idx],q=path[Math.min(idx+1,path.length-1)],dx=q[0]-p[0],dy=q[1]-p[1],len=Math.hypot(dx,dy)||1;let lane=((x-p[0])*(-dy)+(y-p[1])*dx)/len;const r=Math.hypot(x-166,y-33),ang=Math.atan2(y-33,x-166);let moon=r<=20;let city=y>=194;let dark=src[(y*W+x)*4]+src[(y*W+x)*4+1]+src[(y*W+x)*4+2]===0;map.push({s:cum[idx],lane,r,ang,fixed:moon||city||dark,halo:r>20&&r<40&&y<67})}
function render(frame){let c=canvas(),cx=c.getContext('2d'),im=cx.createImageData(W,H),phase=(frame%N)/N;for(let p=0;p<W*H;p++){let m=map[p],i=p*4;for(let k=0;k<4;k++)im.data[i+k]=src[i+k];if(m.fixed)continue;
// Integer number of brush periods per cycle: exact f(0) = f(N).
let a=m.halo ? (m.ang/TAU*8-phase*2+m.r*.047) : (m.s/30-phase*2+m.lane*.055);
let wave=.5+.5*Math.cos(TAU*a),fine=.5+.5*Math.cos(TAU*(a*2+m.lane*.11));
let pulse=Math.pow(wave,5)*(.55+.45*fine);let shade=.64+.36*wave;let strength=pulse*.60;
// Advected highlight packets stay within the original painted ribbons.
let blue=src[i+2],green=src[i+1],red=src[i];let eligible=blue>=green&&blue>red;
for(let k=0;k<3;k++){let value=src[i+k];if(eligible){const highlight=[85,255,255][k];value=value*shade+(highlight-value)*strength;}im.data[i+k]=Math.round(value/85)*85}im.data[i+3]=255;}cx.putImageData(im,0,0);return c}
for(let i=0;i<N;i++)frames.push(quantize(render(i)));
let zero=frames[0].getContext('2d').getImageData(0,0,W,H).data,closing=render(N).getContext('2d').getImageData(0,0,W,H).data;let seam=0,staticChanged=0;for(let i=0;i<zero.length;i++)if(zero[i]!==closing[i])seam++;for(let f of frames){let pixels=f.getContext('2d').getImageData(0,0,W,H).data;for(let p=0;p<map.length;p++)if(map[p].fixed)for(let k=0;k<3;k++)if(pixels[p*4+k]!==src[p*4+k])staticChanged++}
window.flowChecks={seamByteDifferences:seam,staticPixelChannelDifferences:staticChanged,frames:N};
}
Promise.all([load(assets.original),...assets.digits.map(load)]).then(([original,...ds])=>{orig=original;digits=ds;makeFrames(original);frames.forEach((f,i)=>{if(i%4!==0)return;let b=document.createElement('button'),v=canvas();v.getContext('2d').drawImage(f,0,0);b.append(v);b.title='Кадр '+(i+1);b.setAttribute('aria-label',b.title);b.onclick=()=>{pause();index=i;draw()};$('strip').append(b)});window.previewQA={frameCount:frames.length,paletteSize:colors.size,width:200,height:228};document.querySelector('.note').insertAdjacentHTML('beforeend','<br>Проверка: неподвижные слои — '+window.flowChecks.staticPixelChannelDifferences+' изменений; стык цикла — '+window.flowChecks.seamByteDifferences+' отличий.');draw();requestAnimationFrame(tick)}).catch(e=>{$('status').textContent='Ошибка загрузки: '+e.message});
function tick(t){if(playing&&t-last>=1000/Number($('fps').value)){index=(index+1)%48;last=t;draw()}requestAnimationFrame(tick)}
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Пауза':'Воспроизвести';last=performance.now()};$('frame').oninput=e=>{pause();index=Number(e.target.value);draw()};$('time').onchange=draw;$('fps').onchange=draw;$('zoom').onchange=e=>{$('animated').style.width=200*Number(e.target.value)+'px';$('zoomText').textContent=e.target.value+'×'};$('save').onclick=()=>{let a=document.createElement('a');a.download='starry-sky-frame-'+String(index+1).padStart(2,'0')+'.png';a.href=frames[index].toDataURL();a.click()};
</script></html>`;
fs.writeFileSync(path.join(dir,'index.html'),html);
console.log('Created self-contained HTML: '+path.join(dir,'index.html'));
