const fs=require('fs'),path=require('path');
const dir=__dirname;
const data=f=>'data:image/png;base64,'+fs.readFileSync(path.resolve(dir,f)).toString('base64');
const assets={sheet:data('generated-sheet-v2.png'),original:data('../../resources/images/background.png'),digits:[1,0,0,9].map(n=>data('../../resources/images/digits/digit-'+n+'.png'))};
const html=`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Starry Digits · живое небо</title><style>
*{box-sizing:border-box}body{margin:0;background:#10151c;color:#e9edf2;font:16px system-ui}main{max-width:1080px;margin:auto;padding:36px 24px}h1{font-size:32px;margin:8px 0}p{color:#aab7c7;line-height:1.55}.eyebrow{color:#81d9e9;font-size:12px;letter-spacing:2px}.panels{display:flex;gap:32px;flex-wrap:wrap;align-items:start;margin:30px 0}figure{margin:0}figcaption{margin-top:12px;color:#9badbf;font-size:14px}canvas{image-rendering:pixelated;background:black;display:block;max-width:100%;height:auto;border-radius:3px}#animated{width:400px}#original{width:200px}.screen{padding:16px;background:#06080b;border:1px solid #303b49;border-radius:22px;max-width:100%}.controls{display:flex;align-items:center;gap:18px;flex-wrap:wrap;background:#1c2530;padding:18px;border-radius:14px}button,select{font:inherit;color:#f0f4fa;background:#304253;border:1px solid #536779;padding:8px 12px;border-radius:7px;cursor:pointer}label{display:flex;gap:8px;align-items:center}input[type=range]{width:180px;accent-color:#65d5e7}.note{max-width:760px;font-size:14px}.strip{display:flex;overflow:auto;gap:8px;padding:16px 0}.strip button{padding:4px;background:#080d13}.strip canvas{width:80px}.strip button.active{outline:2px solid #65d5e7}#status{font-variant-numeric:tabular-nums;color:#81d9e9}a{color:#81d9e9}</style>
<main><div class="eyebrow">STARRY DIGITS / ANIMATION STUDY 01</div><h1>Живое ночное небо</h1><p>Воздушные потоки Ван Гога · 200 × 228 пикселей · палитра Pebble, до 64 цветов</p>
<div class="panels"><figure><div class="screen"><canvas id="animated" width="200" height="228"></canvas></div><figcaption>Анимация · увеличение <span id="zoomText">2×</span></figcaption></figure><figure><div class="screen"><canvas id="original" width="200" height="228"></canvas></div><figcaption>Исходный фон · 1×</figcaption><p class="note">12 сгенерированных кадров.<br>Время — оригинальные bitmap-цифры.<br>Без сглаживания и смешивания кадров.</p><p id="status">Загрузка…</p></figure></div>
<div class="controls"><button id="play">Пауза</button><label>Кадр <input id="frame" type="range" min="0" max="11" value="0"></label><label>Скорость <select id="fps"><option value="2">2 кадр/с</option><option value="4" selected>4 кадр/с</option><option value="6">6 кадр/с</option><option value="8">8 кадр/с</option><option value="12">12 кадр/с</option></select></label><label><input id="time" type="checkbox" checked>Время</label><label>Масштаб <select id="zoom"><option value="1">1×</option><option value="2" selected>2×</option><option value="3">3×</option></select></label><button id="save">Скачать кадр PNG</button></div>
<div class="strip" id="strip"></div><p class="note">Это черновик для оценки качества, а не анимация, установленная на часы. Генератор слегка меняет контуры луны и мазков: проверьте мерцание, плавность и переход 12 → 1. Расход батареи и воспроизведение на Pebble пока не проверялись.</p></main>
<script>const assets=${JSON.stringify(assets)};
const $=id=>document.getElementById(id);let frames=[],index=0,playing=true,last=0,colors=new Set();const ctx=$('animated').getContext('2d');
const load=src=>new Promise((resolve,reject)=>{let i=new Image;i.onload=()=>resolve(i);i.onerror=reject;i.src=src});
function quantize(c){let x=c.getContext('2d'),d=x.getImageData(0,0,200,228);for(let i=0;i<d.data.length;i+=4){for(let k=0;k<3;k++)d.data[i+k]=Math.round(d.data[i+k]/85)*85;d.data[i+3]=255;colors.add(d.data[i]+','+d.data[i+1]+','+d.data[i+2])}x.putImageData(d,0,0);return c}
function canvas(){let c=document.createElement('canvas');c.width=200;c.height=228;return c}
let digits=[],orig;function overlay(c){if(!$('time').checked)return;digits.forEach((d,i)=>c.drawImage(d,8+(i%2)*48,16+Math.floor(i/2)*58,48,58))}
function draw(){ctx.clearRect(0,0,200,228);ctx.drawImage(frames[index],0,0);overlay(ctx);let o=$('original').getContext('2d');o.clearRect(0,0,200,228);o.drawImage(orig,0,0);overlay(o);$('frame').value=index;$('status').textContent='Кадр '+(index+1)+' / 12 · '+colors.size+' цветов фона · цикл '+(12/Number($('fps').value)).toFixed(1)+' с';document.querySelectorAll('.strip button').forEach((b,i)=>b.classList.toggle('active',i===index))}
function pause(){playing=false;$('play').textContent='Воспроизвести'}
Promise.all([load(assets.sheet),load(assets.original),...assets.digits.map(load)]).then(([sheet,original,...ds])=>{orig=original;digits=ds;for(let r=0;r<4;r++)for(let c=0;c<3;c++){let f=canvas(),fc=f.getContext('2d');fc.imageSmoothingEnabled=false;fc.drawImage(sheet,c*sheet.width/3,r*sheet.height/4,sheet.width/3,sheet.height/4,0,0,200,228);frames.push(quantize(f))}frames.forEach((f,i)=>{let b=document.createElement('button'),v=canvas();v.getContext('2d').drawImage(f,0,0);b.append(v);b.title='Кадр '+(i+1);b.setAttribute('aria-label',b.title);b.onclick=()=>{pause();index=i;draw()};$('strip').append(b)});window.previewQA={frameCount:frames.length,paletteSize:colors.size,width:200,height:228};draw();requestAnimationFrame(tick)}).catch(e=>{$('status').textContent='Ошибка загрузки: '+e.message});
function tick(t){if(playing&&t-last>=1000/Number($('fps').value)){index=(index+1)%12;last=t;draw()}requestAnimationFrame(tick)}
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Пауза':'Воспроизвести';last=performance.now()};$('frame').oninput=e=>{pause();index=Number(e.target.value);draw()};$('time').onchange=draw;$('fps').onchange=draw;$('zoom').onchange=e=>{$('animated').style.width=200*Number(e.target.value)+'px';$('zoomText').textContent=e.target.value+'×'};$('save').onclick=()=>{let a=document.createElement('a');a.download='starry-sky-frame-'+String(index+1).padStart(2,'0')+'.png';a.href=frames[index].toDataURL();a.click()};
</script></html>`;
fs.writeFileSync(path.join(dir,'index.html'),html);
console.log('Created self-contained HTML: '+path.join(dir,'index.html'));
